### PR TITLE
Make it so `testFunction` can throw

### LINKED ISSUE #83: MockService's testFunction should `rethrows`
Hi,

It'd be great if the `testFunction` from the `MockService` could be marked as `rethrows`. 

This will allow us to call throwing functions inside `testFunction`, and for that error to be thrown in turn by the `XCTest` function. Errors thrown from `XCTest` funcs fail the test. It is likely that an exception inside the `testFunction` would be a good enough reason to fail the test. This means we won't have to catch the error if all we wanted to do was fail the test.  

Example of usage would be:
```
    //Run the tests
    animalMockService.run { (testComplete) -> Void in
      let animals = try animalServiceClient.getAlligators()
      XCTAssertTrue(animals.count > 0)
      testComplete()
    }
```

Also means we don't need to use `try!`, which would crash the test.

The standard library uses `rethrows` inside sequence algorithms for things like `flatMap`: https://github.com/apple/swift/blob/master/stdlib/public/core/SequenceAlgorithms.swift#L756

More on `rethrows`: https://docs.swift.org/swift-book/ReferenceManual/Declarations.html and https://www.hackingwithswift.com/example-code/language/how-to-use-the-rethrows-keyword

### PR DESCRIPTION
**Pull request by huwr**
Previously, running the MockService only took a non-throwing closure. This is place in which testers will place their networking requests. It is common for networking requests to throw, however. Not being able to throw in the test function meant testers had to catch and fail their tests on their own:

    myMockService.run(timeout: 10) { (testComplete) -> Void in
      do {
        try serviceClientUnderTest.getUsers( /* ... */ )
      } catch {
        XCTFail("error thrown: \(error.localizedDescription)")
      }
    }

It would be cleaner if `run` would accept a throwing function and fail the test itself. This would become:

    myMockService.run(timeout: 10) { (testComplete) -> Void in
      try serviceClientUnderTest.getUsers( /* ... */ )
    }

__NB:__ I have not made it so that the `run` function rethrows. This proved to be a challenge, and I have not completed it. It could done later on. The main difficulty was my understanding the nesting of call-backs. I wound up having to salt-and-pepper `try`, `throws`, and `rethrows` all over the place; ending up in trouble when `URLSession.dataTask` could not throw its errors, but captured the throwing test function. I have left the branch up: https://github.com/huwr/pact-consumer-swift/tree/huwr/throwing

Resolves #83

### CODE REVIEW

File: Tests/MockServiceSpec.swift [hunk 1]
```diff
@@ -211,5 +211,35 @@ class MockServiceSpec: QuickSpec {
         expect(pactServicePactStub!.writePactStub.requestExecuted).to(equal(true))
       }
     }
+
+    describe("test function throws") {
```
Comment (andrewspinks) [inline Tests/MockServiceSpec.swift]: Maybe:
```
describe("when test function throws error")
...
it("returns message from thrown error")
```

File: Tests/MockServiceSpec.swift [hunk 2]
```diff
@@ -211,5 +211,35 @@ class MockServiceSpec: QuickSpec {
...
+      beforeEach {
+        pactServicePactStub!
+          .clean(responseCode: 200, response: "Cleaned OK")
+          .setupInteractions(responseCode: 200, response: "Setup succeeded")
+      }
+
+      it("calls test function") {
```
Comment (andrewspinks) [inline Tests/MockServiceSpec.swift]: This looks like a duplicated test, please remove.

**Review by andrewspinks — COMMENTED** [review]
The build failed with a linting error.
```
pact-consumer-swift/Sources/MockService.swift:178:1: warning: Line Length Violation: Line should be 128 characters or less: currently 141 characters (line_length)
```
Apologies, its hidden in the build logs. We need to fix that 😬

**Comment by huwr** [comment]
Cool! Thanks for the review, @andrewspinks I've made a few corrections.

**Comment by bethesque** [comment]
Hi @huwr!

**Comment by huwr** [comment]
Hello, @bethesque!

**Review by andrewspinks — APPROVED** [review]

**Comment by huwr** [comment]
Sweet! Thanks @andrewspinks
